### ISSUE TITLE
TypeError: spec() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by akshala** [PAIR-code/lit#228]
Hi.
I have installed lit-nlp and I am trying to run the demo but it is giving an error. I am running it in python version 3.6.5

Command run: python -m demo --port=5432 --model_path=./stackedLSTM.h5

Output:
2021-02-23 15:03:14.331368: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-02-23 15:03:14.331491: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-02-23 15:03:17.705333: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-02-23 15:03:17.710422: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-02-23 15:03:17.764782: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-02-23 15:03:17.764828: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (akshala-VivoBook-ASUSLaptop-X409FA-X409FA): /proc/driver/nvidia/version does not exist
2021-02-23 15:03:17.765222: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-02-23 15:03:17.765649: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
I0223 15:03:19.727962 140484601390912 dev_server.py:86] 
 (    (           
 )\ ) )\ )  *   ) 
(()/((()/(` )  /( 
 /(_))/(_))( )(_))
(_)) (_)) (_(_()) 
| |  |_ _||_   _| 
| |__ | |   | |   
|____|___|  |_|   

I0223 15:03:19.728110 140484601390912 dev_server.py:87] Starting LIT server...
I0223 15:03:19.728195 140484601390912 caching.py:128] CachingModelWrapper 'sarcasm_detect': no cache path specified, not loading.
Traceback (most recent call last):
  File "/home/akshala/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/akshala/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/akshala/Documents/IIITD/TavLab/timeSeries_for_text/LIT/demo.py", line 129, in <module>
    app.run(main)
  File "/home/akshala/Documents/IIITD/TavLab/timeSeries_for_text/LIT/venv/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/akshala/Documents/IIITD/TavLab/timeSeries_for_text/LIT/venv/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/akshala/Documents/IIITD/TavLab/timeSeries_for_text/LIT/demo.py", line 125, in main
    lit_demo.serve()
  File "/home/akshala/Documents/IIITD/TavLab/timeSeries_for_text/LIT/venv/lib/python3.6/site-packages/lit_nlp/dev_server.py", line 88, in serve
    app = lit_app.LitApp(*self._app_args, **self._app_kw)
  File "/home/akshala/Documents/IIITD/TavLab/timeSeries_for_text/LIT/venv/lib/python3.6/site-packages/lit_nlp/app.py", line 339, in __init__
    self._build_metadata()
  File "/home/akshala/Documents/IIITD/TavLab/timeSeries_for_text/LIT/venv/lib/python3.6/site-packages/lit_nlp/app.py", line 94, in _build_metadata
    dname for dname, ds in self._datasets.items()
  File "/home/akshala/Documents/IIITD/TavLab/timeSeries_for_text/LIT/venv/lib/python3.6/site-packages/lit_nlp/app.py", line 95, in <listcomp>
    if mspec.is_compatible_with_dataset(ds.spec())
TypeError: spec() missing 1 required positional argument: 'self'

Could you please help out.

**Comment by jameswex** [comment]
Have you written your own dataset and model wrappers for your use case? What does the Dataset spec method look like for the dataset(s) you are trying to load into LIT? Any code you could provide would be helpful. Thanks.

**Comment by akshala** [comment]
This is the link for the demo.py file: https://drive.google.com/file/d/1cCeQhEkB4CaPiFZm5FkWb9dG4bEWvBIq/view?usp=sharing 
Dataset being used: https://www.kaggle.com/rmisra/news-headlines-dataset-for-sarcasm-detection

**Comment by jameswex** [comment]
Thanks for the code pointer. Your line `datasets = {"sarcasm_data": SarcasmData}` needs to be updated to `datasets = {"sarcasm_data": SarcasmData()}` to instantiate your dataset as the dict of dataset names to datasets should contain instances of your dataset classes. Also you can remove the `split` param from the  Dataset constructor as you aren't using it. Let me know how that goes.

I see your model is returning the Tokens type as output. Tokens are used in LIT to represent the tokenized text, so an input of "hello world" might return a list of tokens of length two containing "hello" and "world". What is your model trying to do? If its a simple classifier, you should use the CategoryLabel type in the output spec, as the SST2 example does.

**Comment by akshala** [comment]
Thank you so much. The error has been resolved.
